version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: app
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: nodemon src/index.ts
